### ISSUE TITLE
What happens after manifest_templates.ipynb?

### ISSUE THREAD

**Issue by htwashere** [tc-ca/TC3oE-Kubernetes#1]
After the jupyter notebook is run, it generates a number of yml files successfully. For example, in the workloads folder, new yaml have been created. My question is: which process will actually execute those yaml files?

**Comment by TeamDman** [comment]
Argocd will be pointed to the directory containing the overlay, the overlays is what is generated by the jupyter notebook. Argo lives in Kubernetes and watches the git repos to identify and rectify drift

**Comment by htwashere** [comment]
Unfortunately, in my case, my app did not appear to get picked up by ArgoCD. I can see that the notebook has generated new yaml files in path https://github.com/tc-ca/TC3oE-Kubernetes/tree/main/shared-cluster/iac-kubernetes/workloads/app-of-apps/overlays/dev_1/demos. I did check the argoCD set up for App-of-Apps, its repo URL and path are pointing correctly to iac-kubernetes/workloads/app-of-apps/overlays/dev_1. But for some reasons, ArgoCD did not seem to want to take action.

I decided to try a manual kubectl apply the generated yaml (kind: Application), kubectl ran successfully.  I now see my app shown in the ArgoCD dashboard, but its status is "unknown". If I do a SyncAll in ArgoCD, my app shows a "Sync Error".

What is the best way to freshen my app deployment?

**Comment by TeamDman** [comment]
The app of apps workload needs to be deployed manually the first time using the control.ps1 script, that will create the resources to tell Argo to look for future changes

**Comment by TeamDman** [comment]
If you click the sync error or something there's a way to get more detailed logs regarding what went wrong. If not, check the logs for the argocd pods

**Comment by htwashere** [comment]
Figured out the issue. Found a couple minor issues with the file paths, and also our repo has some partial configuration for a 3rd environment that is not fully in place. As a result, the notebook picked up the 3rd env and try to perform jinja on it and aborted. The error message was displayed but because the cell display was too long and somehow the error message was not evident. I temporarily remove the 3rd env from the dict and now it is working. Argo is able to auto-sync but I am having some issues with my ACR image. That will be the next debug session!
